const mongoose = require("mongoose");
const Product = require("./models/Product"); // adjust path if needed
require("dotenv").config(); // loads MONGO_URI from your .env

async function seed() {
  try {
    await mongoose.connect(process.env.MONGODB_URI, {
      useNewUrlParser: true,
      useUnifiedTopology: true,
    });
    console.log("MongoDB connected ✅");

    // 🧹 Clear existing data before seeding
    await Product.deleteMany();
    console.log("Existing products cleared");

    const products = [
      {
        name: "Golden Nose Ring",
        category: "Gold",
        subCategory: "Rings",
        weight:0.850,
        description: "A stunning handcrafted gold nose ring",
        imageUrl: "nosering1.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
      {
        name: "Golden Stylish Nose Ring",
        category: "Gold",
        subCategory: "Rings",
        weight:0.960,
        description: "Elegant nose ring with intricate design",
        imageUrl: "nosering2.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
      {
        name: "Golden Pearl Nose Ring",
        category: "Gold",
        subCategory: "Rings",
        weight:1.500,
        description: "Stylish nose ring adorned with pearls",
        imageUrl: "nosering3.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
      {
        name: "Nose Ring",
        category: "Gold",
        subCategory: "Rings",
        weight:1.700,
        description: "Pearl emebelished nose ring",
        imageUrl: "nosering4.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
      {
        name: "Peacock design nose ring",
        category: "Gold",
        subCategory: "Rings",
        weight:1.770,
        description: "Stylish Nose ring with peacock design",
        imageUrl: "nosering5.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
      {
        name: "Golden Tradtional Nose Ring",
        category: "Gold",
        subCategory: "Rings",
        weight:1.280,
        description: "Elegant nose ring with stylish design",
        imageUrl: "nosering6.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
      {
        name: "Gold Nose ring",
        category: "Gold",
        subCategory: "Rings",
        weight:1.400,
        description: "Nose ring with pearl design",
        imageUrl: "nosering7.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
      {
        name: "Golden elegant Nose Ring",
        category: "Gold",
        subCategory: "Rings",
        weight:1.240,
        description: "Stylish nose ring with pearls",
        imageUrl: "nosering8.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
      {
        name: "Golden Stylish Pearl Nose Ring",
        category: "Gold",
        subCategory: "Rings",
        weight:1.440,
        description: "Elegant nose ring with intricate design",
        imageUrl: "nosering9.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
      {
        name: "Golden detailed Nose Ring",
        category: "Gold",
        subCategory: "Rings",
        weight:1.000,
        description: "Stylish rounded nose ring",
        imageUrl: "nosering10.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
      {
        name: "Gold Small Nose Ring",
        category: "Gold",
        subCategory: "Rings",
        weight:0.850,
        description: "Intricate designed nose ring",
        imageUrl: "nosering11.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
      {
        name: "Nose Ring with bird design",
        category: "Gold",
        subCategory: "Rings",
        weight:1.110,
        description: "Stylish bird desgined nose ring",
        imageUrl: "nosering12.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
      {
        name: "Detailed Nose Ring",
        category: "Gold",
        subCategory: "Rings",
        weight:1.510,
        description: "Nose ring with traditional design",
        imageUrl: "nosering13.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
      {
        name: "Classic Band Ring",
        category: "Gold",
        subCategory: "Rings",
        weight:null,
        description: "Heart and 'Namu' engraved band ring",
        imageUrl: "ring1.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
      {
        name: "Floral Spark Gold Ring",
        category: "Gold",
        subCategory: "Rings",
        weight:null,
        description: "Beautiful floral design gold ring",
        imageUrl: "ring2.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
      {
        name: "Pattern Designed Gold Ring",
        category: "Gold",
        subCategory: "Rings",
        weight:null,
        description: "Beautiful motif crafted for everyday elegance.",
        imageUrl: "ring3.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
      {
        name: "Golden Stylish floral Ring",
        category: "Gold",
        subCategory: "Rings",
        weight:null,
        description: "Stunning floral design gold ring",
        imageUrl: "ring4.jpg",
        availableOnline: true,
        featured: true,
        inStock: true,
      },
      {
        name: "Delight floral Gold Ring",
        category: "Gold",
        subCategory: "Rings",
        weight:null,
        description: "Flower pattern designed gold ring",
        imageUrl: "ring5.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
      {
        name: "Ruby Stone Gold Ring",
        category: "Gold",
        subCategory: "Rings",
        weight:null,
        description: "Stunning gold ring adorned with a single bright ruby at the center.",
        imageUrl: "ring6.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
      {
        name: "Classic Gold Ring",
        category: "Gold",
        subCategory: "Rings",
        weight:null,
        description: "Stylish gold ring with yellowish ruby stone in center",
        imageUrl: "ring7.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
      {
        name: "Traditional Carved Gold Ring",
        category: "Gold",
        subCategory: "Rings",
        weight:null,
        description: "Elegant gold ring with Kundan stones",
        imageUrl: "ring8.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
      {
        name: "Kundan Stone Gold Ring",
        category: "Gold",
        subCategory: "Rings",
        weight:null,
        description: "Contemporary gold ring with Kundan stone in center",
        imageUrl: "ring9.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
      {
        name: "Twisted Kundan Gold Ring",
        category: "Gold",
        subCategory: "Rings",
        weight:null,
        description: "Three Kundan stones embedded gold ring",
        imageUrl: "ring10.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
      {
        name: "Elegant Gold Ring",
        category: "Gold",
        subCategory: "Rings",
        weight:null,
        description: "Simple and elegant gold ring design",
        imageUrl: "ring11.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
      {
        name: "Gold round pendant",
        category: "Gold",
        subCategory: "Necklaces",
        weight:null,
        description: "Round pendant with elegant design",
        imageUrl: "pendant1.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
      {
        name: "Gold round detailed pendant",
        category: "Gold",
        subCategory: "Necklaces",
        weight:null,
        description: "Round pendant with red stone in center",
        imageUrl: "pendant2.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
      {
        name: "Lakshmi Devi Pendant",
        category: "Gold",
        subCategory: "Necklaces",
        weight:null,
        description: "Traditional goddess design for divine blessings.",
        imageUrl: "pendant3.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
      {
        name: "Gold rounded design pendant",
        category: "Gold",
        subCategory: "Necklaces",
        weight:null,
        description: "Elegant pendant with rounded desgin and red stones",
        imageUrl: "pendant4.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
      {
        name: "Gold flower design pendant",
        category: "Gold",
        subCategory: "Necklaces",
        weight:null,
        description: "Pendant with flower design and intricate work",
        imageUrl: "pendant5.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
      {
        name: "Pendant with traditional design",
        category: "Gold",
        subCategory: "Necklaces",
        weight:null,
        description: "Traditional round design pendant with red stones",
        imageUrl: "pendant6.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
      {
        name: "Gold  Kundan pendant",
        category: "Gold",
        subCategory: "Necklaces",
        weight:null,
        description: "Traditional gold with colourful Kundan stones",
        imageUrl: "pendant7.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
      {
        name: "Square design pendant",
        category: "Gold",
        subCategory: "Necklaces",
        weight:null,
        description: "Stylish square design pendant with intricate work",
        imageUrl: "pendant8.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
      {
        name: "Gold Mangalsutra pendant",
        category: "Gold",
        subCategory: "Necklaces",
        weight:null,
        description: "Elegant Mangalsutra pendant with pink stones",
        imageUrl: "pendant9.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
      {
        name: "Gold pendant for Mangalsutra",
        category: "Gold",
        subCategory: "Necklaces",
        weight:null,
        description: "Gold detailed Mangalsutra pendant",
        imageUrl: "pendant10.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
      {
        name: "Mangalsutra pendant",
        category: "Gold",
        subCategory: "Necklaces",
        weight:null,
        description: "Mangalsutra pendant with gold detailing",
        imageUrl: "pendant11.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
      {
        name: "Spiral managlsutra pendant",
        category: "Gold",
        subCategory: "Necklaces",
        weight:null,
        description: "Elegant spiral design Mangalsutra pendant",
        imageUrl: "pendant12.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
      {
        name: "Royal Heritage Haar",
        category: "Gold",
        subCategory: "Necklaces",
        weight:null,
        description: "Intricately designed traditional necklace",
        imageUrl: "neck1.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
       {
        name: "Golden 3 layered Necklace",
        category: "Gold",
        subCategory: "Necklaces",
        weight:null,
        description: "Traditional Bead Set",
        imageUrl: "neck2.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
       {
        name: "Golden choker Necklace",
        category: "Gold",
        subCategory: "Necklaces",
        weight:null,
        description: "Choker style necklace with red stone in center",
        imageUrl: "neck3.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
       {
        name: "Golden  beaded Necklace",
        category: "Gold",
        subCategory: "Necklaces",
        weight:null,
        description: "Red stone detailed beaded necklace",
        imageUrl: "neck4.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
       {
        name: "Golden choker style Necklace",
        category: "Gold",
        subCategory: "Necklaces",
        weight:null,
        description: "Delicate choker with intricate design",
        imageUrl: "neck5.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
       {
        name: "Black beaded Mangalsutra Necklace",
        category: "Gold",
        subCategory: "Necklaces",
        weight:null,
        description: "Traditional black beaded mangalsutra with gold detailing",
        imageUrl: "neck6.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
       {
        name: "Gold rounded design necklace",
        category: "Gold",
        subCategory: "Necklaces",
        weight:null,
        description: "Elegant necklace with rounded desgin",
        imageUrl: "neck7.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
       {
        name: "Long coin style Necklace",
        category: "Gold",
        subCategory: "Necklaces",
        weight:null,
        description: "Gold coin design long necklace with laxmi pendant",
        imageUrl: "neck8.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
       {
        name: "Golden detailed traditional Necklace",
        category: "Gold",
        subCategory: "Necklaces",
        weight:null,
        description: "Elegant necklace with heavy design",
        imageUrl: "neck9.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
       {
        name: "Golden choker design Necklace",
        category: "Gold",
        subCategory: "Necklaces",
        weight:15.270,
        description: "Choker style necklace with gold detailing",
        imageUrl: "neck10.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
       {
        name: "Golden flower design Haar",
        category: "Gold",
        subCategory: "Necklaces",
        weight:null,
        description: "Flower detailed traditional haar",
        imageUrl: "neck11.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
       {
        name: "Large choker style Necklace",
        category: "Gold",
        subCategory: "Necklaces",
        weight:null,
        description: "Large detailed choker with red stones flower in center",
        imageUrl: "neck12.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
       {
        name: "Floral Haar Necklace",
        category: "Gold",
        subCategory: "Necklaces",
        weight:null,
        description: "Flower detailed traditional haar",
        imageUrl: "neck13.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
       {
        name: "Golden temple design Necklace",
        category: "Gold",
        subCategory: "Necklaces",
        weight:17.0,
        description: "Temple design traditional gold necklace",
        imageUrl: "neck14.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
       {
        name: "Golden Laxmi Pendant Necklace",
        category: "Gold",
        subCategory: "Necklaces",
        weight:null,
        description: "Tradtional necklace with Laxmi pendant design",
        imageUrl: "neck15.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
       {
        name: "Golden coin style Necklace",
        category: "Gold",
        subCategory: "Necklaces",
        weight:null,
        description: "Coin style necklace with laxmi pendant",
        imageUrl: "neck16.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
       {
        name: "Golden Flower detailed Necklace",
        category: "Gold",
        subCategory: "Necklaces",
        weight:null,
        description: "Floral detailed stones traditional gold necklace",
        imageUrl: "neck17.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
       {
        name: "Golden Heavy choker Necklace",
        category: "Gold",
        subCategory: "Necklaces",
        weight:39.00,
        description:"Heavy choker style necklace with intricate design",
        imageUrl: "neck18.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
       {
        name: "Golden Heavy Necklace with floral design",
        category: "Gold",
        subCategory: "Necklaces",
        weight:41.400,
        description: "Heavy necklace with floral design and intricate work",
        imageUrl: "neck19.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
       {
        name: "Heavy work Golden Necklace",
        category: "Gold",
        subCategory: "Necklaces",
        weight:null,
        description: "Delicate heavy work necklace with traditional design",
        imageUrl: "neck20.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
       {
        name: "Golden red beaded Necklace",
        category: "Gold",
        subCategory: "Necklaces",
        weight:null,
        description: "Two layered red beaded necklace with gold detailing",
        imageUrl: "neck21.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
       {
        name: "Golden Necklace with heavy choker work",
        category: "Gold",
        subCategory: "Necklaces",
        weight:55.00,
        description: "Heavy work choker style necklace with intricate design",
        imageUrl: "neck22.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
       {
        name: "Golden medium sized choker Necklace",
        category: "Gold",
        subCategory: "Necklaces",
        weight:37.800,
        description: "Medium sized choker with traditional floral design",
        imageUrl: "neck23.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
       {
        name: "Medium sized choker Necklace",
        category: "Gold",
        subCategory: "Necklaces",
        weight:44.100,
        description: "Floaral designed medium sized choker with intricate work",
        imageUrl: "neck24.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
       {
        name: "Golden  three layer beaded Necklace",
        category: "Gold",
        subCategory: "Necklaces",
        weight:null,
        description: "Elegant three layers beaded necklace with gold detailing",
        imageUrl: "neck25.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
       {
        name: "Golden peacock design Necklace",
        category: "Gold",
        subCategory: "Necklaces",
        weight:null,
        description: "Temple-style design featuring peacock carvings",
        imageUrl: "neck26.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
      {
        name: "Textured gold hoop earrings",
        category: "Gold",
        subCategory: "Earrings",
        weight:null,
        description: "Gold hoop earrings with heart charms",
        imageUrl: "earring.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
      {
        name: "Traditional design Jhumka",
        category: "Gold",
        subCategory: "Earrings",
        weight:null,
        description: "Simple and elegant jhumka design",
        imageUrl: "earring1.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
      {
        name: "Floral detailed Gold Earrings",
        category: "Gold",
        subCategory: "Earrings",
        weight:null,
        description: "Traditional jhumka with flower design",
        imageUrl: "earring2.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
      {
        name: "Gold Earrings with red stones",
        category: "Gold",
        subCategory: "Earrings",
        weight:null,
        description: "Jhumka style earrings with red stones",
        imageUrl: "earring3.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
      {
        name: "Gold Jhumka Earrings",
        category: "Gold",
        subCategory: "Earrings",
        weight:null,
        description: "Delicate floral dome design with fine filigree work",
        imageUrl: "earring4.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
      {
        name: "Gold detailed Jhumka Earrings",
        category: "Gold",
        subCategory: "Earrings",
        weight:null,
        description: "Stylish jhumka earrings with intricate design",
        imageUrl: "earring5.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
      {
        name: "Traditional detailed Gold Earrings",
        category: "Gold",
        subCategory: "Earrings",
        weight:3.500,
        description: "Detailed jhumka earrings with traditional design",
        imageUrl: "earring6.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
      {
        name: "Gold Jhumka Earring",
        category: "Gold",
        subCategory: "Earrings",
        weight:4.000,
        description: "Elegant jhumka with traditional design",
        imageUrl: "earring7.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
      {
        name: "Jhumka with intricate design",
        category: "Gold",
        subCategory: "Earrings",
        weight:3.900,
        description: "Delicate jhumka earrings with intricate design",
        imageUrl: "earring9.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
      {
        name: "Gold Jhumka with red stones",
        category: "Gold",
        subCategory: "Earrings",
        weight:3.300,
        description: "",
        imageUrl: "earring10.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
      {
        name: "Matte Gold Jhumka",
        category: "Gold",
        subCategory: "Earrings",
        weight:3.400,
        description: "Subtle matte texture for a contemporary edge.",
        imageUrl: "earring11.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
      {
        name: "Small diamond shaped Gold Earrings",
        category: "Gold",
        subCategory: "Earrings",
        weight:null,
        description: "Small and elegant, perfect for daily wear.",
        imageUrl: "earring12.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
      {
        name: "Small round jhumkas",
        category: "Gold",
        subCategory: "Earrings",
        weight:null,
        description: "Small and elegant round jhumkas for everyday wear",
        imageUrl: "earring13.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
      {
        name: "Leaf design Gold Earrings",
        category: "Gold",
        subCategory: "Earrings",
        weight:null,
        description: "Small leaf desgin jhumkas with red stones",
        imageUrl: "earring14.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
      {
        name: "Traditional Design Jhumka",
        category: "Gold",
        subCategory: "Earrings",
        weight:null,
        description: "Intricate pattern work with traditional design",
        imageUrl: "earring15.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
      {
        name: "Temple Lakshmi Jhumka",
        category: "Gold",
        subCategory: "Earrings",
        weight:null,
        description: "Traditional temple-style jhumkas featuring Goddess Lakshmi design.",
        imageUrl: "earring16.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
      {
        name: "Chandbali Jhumka",
        category: "Gold",
        subCategory: "Earrings",
        weight:null,
        description: "Crescent-shaped gold jhumkas with elegant hanging drops.",
        imageUrl: "earring17.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
      {
        name: "Gold Chandbali Earrings",
        category: "Gold",
        subCategory: "Earrings",
        weight:null,
        description: "Crescent-shaped jhumkas with intricate detailing",
        imageUrl: "earring18.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
      {
        name: "Gold chandbali style Earrings",
        category: "Gold",
        subCategory: "Earrings",
        weight:null,
        description: "Crescent moon shaped jhumkas with traditional design",
        imageUrl: "earring19.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
      {
        name: "Traditional Laxmi design Gold Earrings",
        category: "Gold",
        subCategory: "Earrings",
        weight:null,
        description: "Jhumka with Laxmi work and intricate design",
        imageUrl: "earring20.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
      {
        name: "Chandbali studded Gold Earrings",
        category: "Gold",
        subCategory: "Earrings",
        weight:null,
        description: "Crescent shaped jhumkas studded with stones",
        imageUrl: "earring21.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
      {
        name: "Gold leaf shaped Earrings",
        category: "Gold",
        subCategory: "Earrings",
        weight:null,
        description: "Leaf shaped jhumkas with intricate design",
        imageUrl: "earring22.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
      {
        name: "Gold flower shaped Earrings",
        category: "Gold",
        subCategory: "Earrings",
        weight:null,
        description: "Flower shaped jhumkas with traditional design",
        imageUrl: "earring23.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
      {
        name: "Gold Traditional stone Earrings",
        category: "Gold",
        subCategory: "Earrings",
        weight:null,
        description: "Delicate jhumkas with traditional stone setting",
        imageUrl: "earring24.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
      {
        name: "Gold studded Earrings",
        category: "Gold",
        subCategory: "Earrings",
        weight:null,
        description: "Detailed studs with pink stones",
        imageUrl: "earring25.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
      {
        name: "Detailed jhumkas",
        category: "Gold",
        subCategory: "Earrings",
        weight:null,
        description: "Handcrafted jhumka inspired by temple artistry",
        imageUrl: "earring26.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
      {
        name: "Traditional jhumas with intricate design",
        category: "Gold",
        subCategory: "Earrings",
        weight:null,
        description: "Detailed work jhumkas with traditional design",
        imageUrl: "earring27.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
      {
        name: "Small earrings with stone in center",
        category: "Gold",
        subCategory: "Earrings",
        weight:null,
        description: "Stone studded small jhumkas with elegant design",
        imageUrl: "earring28.jpg",
        availableOnline: true,
        featured: true,
        inStock: true,
      },
      {
        name: "Gold double layered Earrings",
        category: "Gold",
        subCategory: "Earrings",
        weight:null,
        description: "Pure gold double layered jhumkas",
        imageUrl: "earring29.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
      {
        name: "Gold round small Earrings",
        category: "Gold",
        subCategory: "Earrings",
        weight:null,
        description: "Floral patterned small round jhumkas",
        imageUrl: "earring30.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
      {
        name: "Golden layered Earrings",
        category: "Gold",
        subCategory: "Earrings",
        weight:null,
        description: "Gold layered jhumkas with traditional design",
        imageUrl: "earring31.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
      {
        name: "Gold drop Earrings",
        category: "Gold",
        subCategory: "Earrings",
        weight:null,
        description: "Elegant drop-style earrings with intricate filigree work",
        imageUrl: "earring32.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
      
      {
        name: "Red stone stud Earrings",
        category: "Gold",
        subCategory: "Earrings",
        weight:null,
        description: "Small red stone studded earrings for daily wear",
        imageUrl: "earring34.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
     {
        name: "Studs Earrings",
        category: "Gold",
        subCategory: "Earrings",
        weight:null,
        description: "Small flower shaped studs with red motis",
        imageUrl: "earring35.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
      {
        name: "Gold Studs",
        category: "Gold",
        subCategory: "Earrings",
        weight:null,
        description: "Detailed studs with green, red and white motis",
        imageUrl: "earring36.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
      {
        name: "Gold stud ",
        category: "Gold",
        subCategory: "Earrings",
        weight:null,
        description: "Floral designed studs with red and white motis",
        imageUrl: "earring37.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
      {
        name: "Intricate design jhumkas",
        category: "Gold",
        subCategory: "Earrings",
        weight:null,
        description: "Detailed jhumkas with red and white motis in center",
        imageUrl: "earring38.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
      {
        name: "Gold red studs",
        category: "Gold",
        subCategory: "Earrings",
        weight:null,
        description: "Sharp gold edged studs with red stone",
        imageUrl: "earring39.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
      {
        name: "Gold Long detailed Earrings",
        category: "Gold",
        subCategory: "Earrings",
        weight:null,
        description: "Temple inspired long jhumkas with intricate design",
        imageUrl: "earring40.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
      {
        name: "Gold double layered Earrings",
        category: "Gold",
        subCategory: "Earrings",
        weight:null,
        description: "Elegant double layered jhumkas with red and green stones",
        imageUrl: "earring41.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
      {
        name: "Gold heart shaped Earrings",
        category: "Gold",
        subCategory: "Earrings",
        weight:null,
        description: "Rich old-gold tone, bold and rustic heart-shaped design",
        imageUrl: "earring42.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
      {
        name: "Jhumka with gold beads",
        category: "Gold",
        subCategory: "Earrings",
        weight:null,
        description: "Delicate jhumka with gold bead hangings",
        imageUrl: "earring43.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
      {
        name: "Gold stone studded Earrings",
        category: "Gold",
        subCategory: "Earrings",
        weight:null,
        description: "Earrings with red and green stone and gold bead hangings",
        imageUrl: "earring44.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
      {
        name: "Gold Circle Earrings",
        category: "Gold",
        subCategory: "Earrings",
        weight:null,
        description: "Classy circular design with intricate patterns",
        imageUrl: "earring45.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
      {
        name: "Golden hoop Earrings",
        category: "Gold",
        subCategory: "Earrings",
        weight:null,
        description: "Simple hoop earrings with elegant design",
        imageUrl: "earring46.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
      {
        name: "Dangling Hoop Gold Earrings",
        category: "Gold",
        subCategory: "Earrings",
        weight:null,
        description: "Golden hoops with bead danglings for a chic look",
        imageUrl: "earring47.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
      {
        name: "Gold detailed hoop Earrings",
        category: "Gold",
        subCategory: "Earrings",
        weight:null,
        description: "Hoop earrings with intricate detailed design",
        imageUrl: "earring48.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
      {
        name: "Gold crescent hoop Earrings",
        category: "Gold",
        subCategory: "Earrings",
        weight:null,
        description: "Crescent-shaped hoop earrings with elegant design",
        imageUrl: "earring49.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
      {
        name: "Gold Traditional Bangles",
        category: "Gold",
        subCategory: "Bracelets",
        weight:null,
        description: "Detailed traditional bangles with red stones",
        imageUrl: "brace1.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
       {
        name: "Gold twisted design Bangles",
        category: "Gold",
        subCategory: "Bracelets",
        weight:null,
        description: "Delicate twisted design bangles with intricate work",
        imageUrl: "brace2.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
       {
        name: "Gold Kada Bracelet",
        category: "Gold",
        subCategory: "Bracelets",
        weight:null,
        description: "Simple yet elegant gold kada bracelet",
        imageUrl: "brace3.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
       {
        name: "Golden Anklet",
        category: "Gold",
        subCategory: "Anklets",
        weight:null,
        description: "detailed traditional anklet with intricate design",
        imageUrl: "anklet1.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },




      {
        name: "Silver Anklet",
        category: "Silver",
        subCategory: "Anklets",
        weight: 1.510,
        description: "Elegant anklet with intricate design  ",
        imageUrl: "silanklet.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
      
      {
        name: "Classic Silver Bracelet",
        category: "Silver",
        subCategory: "Bracelets",
        weight:null,
        description: "Classic silver bracelet with a sleek design",
        imageUrl: "silbrace.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },


      {
        name: "Silver detailed Bracelet ",
        category: "Silver",
        subCategory: "Bracelets",
        weight:null,
        description: "Simple silver bracelet with intricate detailing",
        imageUrl: "silbrace1.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },


      {
        name: "Silver twisted Bracelet",
        category: "Silver",
        subCategory: "Bracelets",
        weight:null,
        description: "Delicate twisted design silver bracelet",
        imageUrl: "silbrace2.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
      {
        name: "Silver Watch",
        category: "Silver",
        subCategory: "Bracelets",
        weight:null,
        description: "Elegant silver watch with intricate design",
        imageUrl: "silbrace3.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
      {
        name: "Watch with silver straps",
        category: "Silver",
        subCategory: "Bracelets",
        weight:null,
        description: "Elegant silver watch with intricate design",
        imageUrl: "silbrace4.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
      {
        name: "Vintage Silver Watch",
        category: "Silver",
        subCategory: "Bracelets",
        weight:null,
        description: "Delicate vintage-style silver watch with detailed design",
        imageUrl: "silbrace5.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
      {
        name: "Silver Vintage watch bracelet",
        category: "Silver",
        subCategory: "Bracelets",
        weight:null,
        description: "Vintage-style silver watch with intricate bracelet design",
        imageUrl: "silbrace6.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
      
      {
        name: "Simple Silver Necklace",
        category: "Silver",
        subCategory: "Necklaces",
        weight:null,
        description: "Elegant silver necklace with intricate design",
        imageUrl: "silneck1.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
       {
        name: "Silver beaded Necklace",
        category: "Silver",
        subCategory: "Necklaces",
        weight:null,
        description: "Simple yellow and red beaded silver necklace with elegant design",
        imageUrl: "silneck2.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
       {
        name: "Silver detailed Necklace",
        category: "Silver",
        subCategory: "Necklaces",
        weight:null,
        description: "Elegant silver necklace with intricate design",
        imageUrl: "silneck3.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
       {
        name: "Necklace with pointed design",
        category: "Silver",
        subCategory: "Necklaces",
        weight:null,
        description: "Pointed design silver necklace with intricate work",
        imageUrl: "silneck4.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
       {
        name: "Silver Flower Necklace",
        category: "Silver",
        subCategory: "Necklaces",
        weight:null,
        description: "Beautiful flower designed silver necklace",
        imageUrl: "silneck5.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
       {
        name: "Silver  beads design Necklace",
        category: "Silver",
        subCategory: "Necklaces",
        weight:null,
        description: "Elegant necklace with simple bead design",
        imageUrl: "neck6.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
       {
        name: "Silver Flower detailed Necklace",
        category: "Silver",
        subCategory: "Necklaces",
        weight:null,
        description: "Beautiful flower designed silver necklace",
        imageUrl: "silneck7.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
       {
        name: "Heavy Silver Necklace",
        category: "Silver",
        subCategory: "Necklaces",
        weight:null,
        description: "Heavy silver necklace with flower pendant design",
        imageUrl: "silneck8.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
       {
        name: "Floral Necklace",
        category: "Silver",
        subCategory: "Necklaces",
        weight:null,
        description: "Floral pendant desgined silver necklace",
        imageUrl: "silneck9.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
       {
        name: "Silver blue flower Necklace",
        category: "Silver",
        subCategory: "Necklaces",
        weight:null,
        description: "Pretty blue flower designed silver necklace with flower pendant",
        imageUrl: "silneck10.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
       {
        name: "Silver red flower Necklace",
        category: "Silver",
        subCategory: "Necklaces",
        weight:null,
        description: "Delicate red flower pendant design silver necklace",
        imageUrl: "silneck11.jpg",
        availableOnline: true,
        featured: true,
        inStock: true,
      },
       {
        name: "Silver Necklace with flower pendant",
        category: "Silver",
        subCategory: "Necklaces",
        weight:null,
        description: "Elegant silver necklace with red stone floral design",
        imageUrl: "silneck12.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
       {
        name: "Flower detailed Necklace",
        category: "Silver",
        subCategory: "Necklaces",
        weight:null,
        description: "Flower detailed silver necklace with intricate design",
        imageUrl: "silneck13.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
       {
        name: "Silver Pink Floral Necklace",
        category: "Silver",
        subCategory: "Necklaces",
        weight:null,
        description: "Pink flower designed silver necklace with elegant design",
        imageUrl: "silneck15.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
       {
        name: "Silver flower pendant Necklace",
        category: "Silver",
        subCategory: "Necklaces",
        weight:null,
        description: "Stlylish silver necklace with flower pendant design",
        imageUrl: "silneck16.jpg",
        availableOnline: true,
        featured: true,
        inStock: true,
      },
       {
        name: "Heavy work silver necklace",
        category: "Silver",
        subCategory: "Necklaces",
        weight:null,
        description: "Rounded heavy work silver necklace with intricate design",
        imageUrl: "silneck17.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
       {
        name: "Silver Necklace with round pendant",
        category: "Silver",
        subCategory: "Necklaces",
        weight:null,
        description: "Rounded pendant with green stone necklace",
        imageUrl: "silneck18.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
       {
        name: "Silver Mangalsutra",
        category: "Silver",
        subCategory: "Necklaces",
        weight:null,
        description: "Black beaded mangalsutra with silver pendant",
        imageUrl: "silneck19.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
       {
        name: "One layer Mangalsutra",
        category: "Silver",
        subCategory: "Necklaces",
        weight:null,
        description: "Mangalsutra with single layer black beads and silver pendant",
        imageUrl: "silneck20.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
       {
        name: "Single layer Mangalsutra",
        category: "Silver",
        subCategory: "Necklaces",
        weight:null,
        description: "Mangalsutra with single layer black beads and delicate silver pendant",
        imageUrl: "silneck21.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
       {
        name: "Silver Mukhota",
        category: "Silver",
        subCategory: "Pooja Silverware",
        weight:null,
        description: "Yellamma Devi silver mukhota for pooja rituals",
        imageUrl: "random.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
       {
        name: "Silver Lotus Holders",
        category: "Silver",
        subCategory: "Pooja Silverware",
        weight:null,
        description: "Elegant silver lotus holders for pooja rituals",
        imageUrl: "random1.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
       {
        name: "Silver Aarti Thali",
        category: "Silver",
        subCategory: "Pooja Silverware",
        weight:null,
        description: "Traditional silver aarti thali for pooja rituals",
        imageUrl: "random2.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
       {
        name: "Silver Design Thali",
        category: "Silver",
        subCategory: "Pooja Silverware",
        weight:null,
        description: "Elegant silver thali with intricate design for pooja rituals",
        imageUrl: "random3.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
       {
        name: "Silver Pooja Bells",
        category: "Silver",
        subCategory: "Pooja Silverware",
        weight:null,
        description: "Traditional silver pooja bells for rituals",
        imageUrl: "random4.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
       {
        name: "Silver Goddess Figurine",
        category: "Silver",
        subCategory: "Pooja Silverware",
        weight:null,
        description: "Renuka Yellamma Devi silver figurine for pooja rituals",
        imageUrl: "random5.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
       {
        name: "Silver kumkum box with lid",
        category: "Silver",
        subCategory: "Pooja Silverware",
        weight:null,
        description: "Small Kumkum box with lid for pooja rituals",
        imageUrl: "random6.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
       {
        name: "Small Silver Kumkum box",
        category: "Silver",
        subCategory: "Pooja Silverware",
        weight:null,
        description: "Small kumkum box for pooja rituals",
        imageUrl: "random7.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
       {
        name: "Silver Ganesh Figurine",
        category: "Silver",
        subCategory: "Pooja Silverware",
        weight:null,
        description: "Small silver figurine of Lord Ganesha for pooja rituals",
        imageUrl: "random8.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
       {
        name: "Silver Sindoor box",
        category: "Silver",
        subCategory: "Pooja Silverware",
        weight:null,
        description: "Sindoor box with applicator for pooja rituals",
        imageUrl:"random9.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
       {
        name: "Silver Diya Lamp",
        category: "Silver",
        subCategory: "Pooja Silverware",
        weight:null,
        description: "Elegant silver diya lamp for pooja rituals",
        imageUrl: "random10.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
       {
        name: "Silver delicate detailed Ganesha Figurine",
        category: "Silver",
        subCategory: "Pooja Silverware",
        weight:null,
        description: "Delicate detailed silver figurine of Lord Ganesha for pooja rituals",
        imageUrl: "random11.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
       {
        name: "Detailed Silver Ganesha Figurine",
        category: "Silver",
        subCategory: "Pooja Silverware",
        weight:null,
        description: "Detailed silver figurine of Lord Ganesha for pooja rituals",
        imageUrl: "random12.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
       {
        name: "Silver Colored Flowers",
        category: "Silver",
        subCategory: "Pooja Silverware",
        weight:null,
        description: "Elegant silver colored flowers for pooja rituals",
        imageUrl: "random13.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
       {
        name: "Silver Modaks",
        category: "Silver",
        subCategory: "Pooja Silverware",
        weight:null,
        description: "Silver modaks for pooja rituals",
        imageUrl: "random14.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
       {
        name: "Silver Trishul",
        category: "Silver",
        subCategory: "Pooja Silverware",
        weight:null,
        description: "Silver trishul for pooja rituals",
        imageUrl: "random15.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
       {
        name: "Silver Ganesh Figurine",
        category: "Silver",
        subCategory: "Pooja Silverware",
        weight:null,
        description: "Silver figurine of Lord Ganesha for pooja rituals",
        imageUrl: "random16.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
       {
        name: "Decorative bowls",
        category: "Silver",
        subCategory: "Pooja Silverware",
        weight:null,
        description: "Decorative silver bowls for pooja rituals",
        imageUrl: "random18.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
       {
        name: "Simple design pooja lamps",
        category: "Silver",
        subCategory: "Pooja Silverware",
        weight:null,
        description: "Simple silver lamps for diya lighting during pooja",
        imageUrl: "random19.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
       {
        name: "Silver Peacock Lamps",
        category: "Silver",
        subCategory: "Pooja Silverware",
        weight:null,
        description: "Peacock designed silver lamps for pooja",
        imageUrl: "random20.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
       {
        name: "Peacock designed kumkum box",
        category: "Silver",
        subCategory: "Pooja Silverware",
        weight:null,
        description: "Peacock designed silver kumkum box for pooja",
        imageUrl: "random21.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
       {
        name: "Silver detailed kumkum box",
        category: "Silver",
        subCategory: "Pooja Silverware",
        weight:null,
        description: "Delicate design silver kumkum box for pooja",
        imageUrl: "random22.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
       {
        name: "Silver two piece kumkum box",
        category: "Silver",
        subCategory: "Pooja Silverware",
        weight:null,
        description: "Color detailed two piece silver kumkum box for pooja",
        imageUrl: "random23.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
       {
        name: "Four piece detailed silver kumkum box",
        category: "Silver",
        subCategory: "Pooja Silverware",
        weight:null,
        description: "Detailed silver kumkum box with four compartments for pooja",
        imageUrl: "random24.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
       {
        name: "Silver Three piece kumkum box",
        category: "Silver",
        subCategory: "Pooja Silverware",
        weight:null,
        description: "Three piece silver kumkum box for pooja",
        imageUrl: "random25.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
       {
        name: "Four piece kumkum set",
        category: "Silver",
        subCategory: "Pooja Silverware",
        weight:null,
        description: "Four piece silver kumkum set for pooja",
        imageUrl: "random26.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
       {
        name: "Silver kumkum box for religious ceremonies",
        category: "Silver",
        subCategory: "Pooja Silverware",
        weight:null,
        description: "Kumkum box for pooja and religious ceremonies",
        imageUrl: "random27.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
       {
        name: "Design Silver two tier bowl",
        category: "Silver",
        subCategory: "Pooja Silverware",
        weight:null,
        description: "Two tiered pooja bowl for religious ceremonies",
        imageUrl: "random28.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
       {
        name: "Silver two tiered bowl",
        category: "Silver",
        subCategory: "Pooja Silverware",
        weight:null,
        description: "Two tiered silver bowl for pooja",
        imageUrl: "random29.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
       {
        name: "Silver two-bowl serving stand",
        category: "Silver",
        subCategory: "Pooja Silverware",
        weight:null,
        description: "Two bowl silver serving stand for pooja",
        imageUrl: "random30.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
       {
        name: "Heart shaped kumkum box",
        category: "Silver",
        subCategory: "Pooja Silverware",
        weight:null,
        description: "Heart shaped silver kumkum box for pooja",
        imageUrl: "random31.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
       {
        name: "Silver kumkum box for pooja",
        category: "Silver",
        subCategory: "Pooja Silverware",
        weight:null,
        description: "Pooja kumkum box",
        imageUrl: "random32.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
       {
        name: "Two tier Silver Kumkum box",
        category: "Silver",
        subCategory: "Pooja Silverware",
        weight:null,
        description: "Two tier kumkum box with intricate silver design",
        imageUrl: "random33.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
       {
        name: "Silver elephant leg bowl",
        category: "Silver",
        subCategory: "Pooja Silverware",
        weight:null,
        description: "Religious silver bowl with elephant leg design",
        imageUrl: "random34.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
       {
        name: "Silver bowl on stand",
        category: "Silver",
        subCategory: "Pooja Silverware",
        weight:null,
        description: "Silver bowl on a pedestal stand for pooja",
        imageUrl: "random35.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
       {
        name: "Silver Matka",
        category: "Silver",
        subCategory: "Pooja Silverware",
        weight:null,
        description: "Medium sized silver matka for pooja",
        imageUrl: "random36.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
       {
        name: "Silver Decorative showpiece",
        category: "Silver",
        subCategory: "Pooja Silverware",
        weight:null,
        description: "Silver decorative showpiece with intricate design",
        imageUrl: "random37.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
       {
        name: "Candle Holder",
        category: "Silver",
        subCategory: "Pooja Silverware",
        weight:null,
        description: "Medium sized silver candle holder",
        imageUrl: "random38.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
       {
        name: "Silver Candle holders",
        category: "Silver",
        subCategory: "Pooja Silverware",
        weight:null,
        description: "Candle holders of different sizes",
        imageUrl: "random39.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
       {
        name: "Silver Kumkum box",
        category: "Silver",
        subCategory: "Pooja Silverware",
        weight:null,
        description: "Kumkum box with intricate silver design",
        imageUrl: "random40.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
       {
        name: "Silver decorative detailed kumkum box",
        category: "Silver",
        subCategory: "Pooja Silverware",
        weight:null,
        description: "Small detailed silver decorative box for kumkum",
        imageUrl: "random41.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
       {
        name: "Decorative bowl",
        category: "Silver",
        subCategory: "Pooja Silverware",
        weight:null,
        description: "Loutus designed silver decorative bowl",
        imageUrl: "random42.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
       {
        name: "Silver Decorative Bowl",
        category: "Silver",
        subCategory: "Pooja Silverware",
        weight:null,
        description: "Elephant designed silver decorative bowl",
        imageUrl: "random43.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
       {
        name: "Silver peacock diya",
        category: "Silver",
        subCategory: "Pooja Silverware",
        Weight:null,
        description: "Common motif silver peacock diya for pooja",
        imageUrl: "random44.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
       {
        name: "Silver Pooja Lamp",
        category: "Silver",
        subCategory: "Pooja Silverware",
        weight:null,
        description: "Detailed silver pooja lamp with intricate design",
        imageUrl: "random45.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
       {
        name: "Silver Handi Bowl with lines",
        category: "Silver",
        subCategory: "Pooja Silverware",
        weight:null,
        description: "Elegant anklet with intricate design",
        imageUrl: "random46.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
       {
        name: "Silver Handi bowl",
        category: "Silver",
        subCategory: "Pooja Silverware",
        weight:null,
        description: "Medium sized silver handi bowl",
        imageUrl: "random47.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },
       {
        name: "Silver Handi",
        category: "Silver",
        subCategory: "Pooja Silverware",
        weight: null,
        description: "Medium sized silver handi",
        imageUrl: "random48.jpg",
        availableOnline: true,
        featured: false,
        inStock: true,
      },

    ];

const seedProducts = async () => {
  try {
    await Product.deleteMany(); // clears existing products
    const created = await Product.insertMany(products);
    console.log(`Seeded ${created.length} products successfully`);
  } catch (err) {
    console.error(err);
    throw err;
  }
}

await seedProducts();
mongoose.connection.close();
  } catch (err) {
    console.error(err);
    mongoose.connection.close();
  }
}

seed();
